name: load-testing-ci

on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/load-testing-ci.yml
    - load-testing/**
env:
  IMAGE_NAME: eshop-load-testing

jobs:
  PublishImage:
    name: Build & Push Container Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_ENDPOINT }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Docker build ${{ env.IMAGE_NAME }}
      run: sudo -E docker build .
      working-directory: ./load-testing
      shell: bash
      env:
        TAG: build.${{ github.run_number }}
        REGISTRY: ${{ secrets.REGISTRY_ENDPOINT }}
    - name: Docker push ${{ env.IMAGE_NAME }}
      run: sudo -E docker push ${{ env.IMAGE_NAME }}
      working-directory: ./load-testing
      shell: bash
      env:
        TAG: build.${{ github.run_number }}
        REGISTRY: ${{ secrets.REGISTRY_ENDPOINT }}
