name: load-testing-ci

on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/load-testing-ci.yml
    - load-testing/**
    - pulumi/load-testing/**
env:
  IMAGE_NAME: eshop-load-testing

jobs:
  PublishImage:
    name: Build & Push Container Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_ENDPOINT }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: ./load-testing
        file: ./load-testing/Dockerfile
        push: true
        tags: |
          ${{ secrets.REGISTRY_ENDPOINT}}/${{ env.IMAGE_NAME }}:build.${{ github.run_number }}
  deploy:
    name: Deploy
    needs: PublishImage
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Install Pulumi CLI
      uses: pulumi/action-install-pulumi-cli@v1.0.1
    - name: Pulumi up
      run: |
        echo "${{secrets.KUBECONFIG}}" > .kubeconfig
        npm install
        pulumi stack select sandbox
        pulumi up --yes --skip-preview --suppress-permalink="true"
      working-directory: ./pulumi/load-testing
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        KUBECONFIG: .kubeconfig
        IMAGE_VERSION: build.${{ github.run_number }}

